program eebu;

uses
  Vcl.Forms,
  udmRepository in 'dm\udmRepository.pas' {dmRepository: TDataModule},
  uformAuthLogin in 'form\uformAuthLogin.pas',
  uformBase in 'form\uformBase.pas' {formBase},
  uformBloqueio in 'form\uformBloqueio.pas' {formBloqueio},
  uformBoletoCreateEdit in 'form\uformBoletoCreateEdit.pas' {formBoletoCreateEdit},
  uformBoletoRemessaList in 'form\uformBoletoRemessaList.pas' {formBoletoRemessaList},
  uformBoletoRetornoList in 'form\uformBoletoRetornoList.pas' {formBoletoRetornoList},
  uformCartaoCreateEdit in 'form\uformCartaoCreateEdit.pas' {formCartaoCreateEdit},
  uformCartaoList in 'form\uformCartaoList.pas' {formCartaoList},
  uformCartaoParcelamento in 'form\uformCartaoParcelamento.pas' {formCartaoParcelamento},
  uformCategoriaCreateEdit in 'form\uformCategoriaCreateEdit.pas' {formCategoriaCreateEdit},
  uformCategoriaList in 'form\uformCategoriaList.pas' {formCategoriaList},
  uformCedenteCreateEdit in 'form\uformCedenteCreateEdit.pas' {formCedenteCreateEdit},
  uformCompraCreateEdit in 'form\uformCompraCreateEdit.pas' {formCompraCreateEdit},
  uformCompraFinalizar in 'form\uformCompraFinalizar.pas' {formCompraFinalizar},
  uformCompraItensAjuste in 'form\uformCompraItensAjuste.pas' {formCompraItensAjuste},
  uformCompraList in 'form\uformCompraList.pas' {formCompraList},
  uformCompraOrcamentoList in 'form\uformCompraOrcamentoList.pas' {formCompraOrcamentoList},
  uformConfiguracaoFiscalCreateEdit in 'form\uformConfiguracaoFiscalCreateEdit.pas' {formConfiguracaoFiscalCreateEdit},
  uformConfiguracaoFiscalIcmsCreateEdit in 'form\uformConfiguracaoFiscalIcmsCreateEdit.pas' {formConfiguracaoFiscalIcmsCreateEdit},
  uformConfiguracaoFiscalList in 'form\uformConfiguracaoFiscalList.pas' {formConfiguracaoFiscalList},
  uformContabilistaCreateEdit in 'form\uformContabilistaCreateEdit.pas' {formContabilistaCreateEdit},
  uformContaCreateEdit in 'form\uformContaCreateEdit.pas' {formContaCreateEdit},
  uformContaList in 'form\uformContaList.pas' {formContaList},
  uformDescription in 'form\uformDescription.pas' {formDescription},
  uformEmpresaConfiguracaoCreateEdit in 'form\uformEmpresaConfiguracaoCreateEdit.pas' {formEmpresaConfiguracaoCreateEdit},
  uformEmpresaCreateEdit in 'form\uformEmpresaCreateEdit.pas' {formEmpresaCreateEdit},
  uformEstoqueList in 'form\uformEstoqueList.pas' {formEstoqueList},
  uformFormaRecebimentoCreateEdit in 'form\uformFormaRecebimentoCreateEdit.pas' {formFormaRecebimentoCreateEdit},
  uformFormaRecebimentoList in 'form\uformFormaRecebimentoList.pas' {formFormaRecebimentoList},
  uformGrupoTributarioCreateEdit in 'form\uformGrupoTributarioCreateEdit.pas' {formGrupoTributarioCreateEdit},
  uformGrupoTributarioList in 'form\uformGrupoTributarioList.pas' {formGrupoTributarioList},
  uformInfadfiscoCreateEdit in 'form\uformInfadfiscoCreateEdit.pas' {formInfadfiscoCreateEdit},
  uformInfadfiscoList in 'form\uformInfadfiscoList.pas' {formInfadfiscoList},
  uformInfCplCreateEdit in 'form\uformInfCplCreateEdit.pas' {formInfCplCreateEdit},
  uformInfCplList in 'form\uformInfCplList.pas' {formInfCplList},
  uformItemCreateEdit in 'form\uformItemCreateEdit.pas' {formItemCreateEdit},
  uformItemInventarioCreate in 'form\uformItemInventarioCreate.pas' {formItemInventarioCreate},
  uformItemList in 'form\uformItemList.pas' {formItemList},
  uformItemMovimentoList in 'form\uformItemMovimentoList.pas' {formItemMovimentoList},
  uformItemUnidadeConversorCreateEdit in 'form\uformItemUnidadeConversorCreateEdit.pas' {formItemUnidadeConversorCreateEdit},
  uformItemUnidadeConversorList in 'form\uformItemUnidadeConversorList.pas' {formItemUnidadeConversorList},
  uformMensagem in 'form\uformMensagem.pas' {formMensagem},
  uformModelo in 'form\uformModelo.pas' {formModelo},
  uformNcmIBPTax in 'form\uformNcmIBPTax.pas' {formNcmIBPTax},
  uformNfeConfiguracaoCreateEdit in 'form\uformNfeConfiguracaoCreateEdit.pas' {formNfeConfiguracaoCreateEdit},
  uformNfeCreateEdit in 'form\uformNfeCreateEdit.pas' {formNfeCreateEdit},
  uformNfeDetCreateEdit in 'form\uformNfeDetCreateEdit.pas' {formNfeDetCreateEdit},
  uformNfeEmpresaList in 'form\uformNfeEmpresaList.pas' {formNfeEmpresaList},
  uformNfeList in 'form\uformNfeList.pas' {formNfeList},
  uformNfeNumeroCreateEdit in 'form\uformNfeNumeroCreateEdit.pas' {formNfeNumeroCreateEdit},
  uformNfeNumeroList in 'form\uformNfeNumeroList.pas' {formNfeNumeroList},
  uformNfeRecebidaDetEdit in 'form\uformNfeRecebidaDetEdit.pas' {formNfeRecebidaDetEdit},
  uformNfeRecebidaDetList in 'form\uformNfeRecebidaDetList.pas' {formNfeRecebidaDetList},
  uformNfeRecebidasList in 'form\uformNfeRecebidasList.pas' {formNfeRecebidasList},
  uformOperacaoFiscalCreateEdit in 'form\uformOperacaoFiscalCreateEdit.pas' {formOperacaoFiscalCreateEdit},
  uformOperacaoFiscalList in 'form\uformOperacaoFiscalList.pas' {formOperacaoFiscalList},
  uformOrcamentoList in 'form\uformOrcamentoList.pas' {formOrcamentoList},
  uformPagamentoCreateEdit in 'form\uformPagamentoCreateEdit.pas' {formPagamentoCreateEdit},
  uformPagamentoList in 'form\uformPagamentoList.pas' {formPagamentoList},
  uformPermissionCreateEdit in 'form\uformPermissionCreateEdit.pas' {formPermissionCreateEdit},
  uformPermissionList in 'form\uformPermissionList.pas' {formPermissionList},
  uformPessoaCreateEdit in 'form\uformPessoaCreateEdit.pas' {formPessoaCreateEdit},
  uformPessoaList in 'form\uformPessoaList.pas' {formPessoaList},
  uformPrincipal in 'form\uformPrincipal.pas' {formPrincipal},
  uformPrint in 'form\uformPrint.pas' {formPrint},
  uformRecebimentoCreateEdit in 'form\uformRecebimentoCreateEdit.pas' {formRecebimentoCreateEdit},
  uformRecebimentoList in 'form\uformRecebimentoList.pas' {formRecebimentoList},
  uformRoleCreateEdit in 'form\uformRoleCreateEdit.pas' {formRoleCreateEdit},
  uformRoleList in 'form\uformRoleList.pas' {formRoleList},
  uformSPEDCreateEdit in 'form\uformSPEDCreateEdit.pas' {formSPEDCreateEdit},
  uformSPEDList in 'form\uformSPEDList.pas' {formSPEDList},
  uformTerminalCreateEdit in 'form\uformTerminalCreateEdit.pas' {formTerminalCreateEdit},
  uformTerminalList in 'form\uformTerminalList.pas' {formTerminalList},
  uformTurnoCreateEdit in 'form\uformTurnoCreateEdit.pas' {formTurnoCreateEdit},
  uformTurnoList in 'form\uformTurnoList.pas' {formTurnoList},
  uformUnidadeCreateEdit in 'form\uformUnidadeCreateEdit.pas' {formUnidadeCreateEdit},
  uformUnidadeList in 'form\uformUnidadeList.pas' {formUnidadeList},
  uformUserCreateEdit in 'form\uformUserCreateEdit.pas' {formUserCreateEdit},
  uformUserList in 'form\uformUserList.pas' {formUserList},
  uformVendaCreateEdit in 'form\uformVendaCreateEdit.pas' {formVendaCreateEdit},
  uformVendaFinalizar in 'form\uformVendaFinalizar.pas' {formVendaFinalizar},
  uformVendaList in 'form\uformVendaList.pas' {formVendaList},
  uformVendaParcelamento in 'form\uformVendaParcelamento.pas' {formVendaParcelamento},
  CustomEditHelper in 'helper\CustomEditHelper.pas',
  Helper in 'helper\Helper.pas',
  Boleto in 'model\Boleto.pas',
  BoletoConfiguracao in 'model\BoletoConfiguracao.pas',
  BoletoRemessa in 'model\BoletoRemessa.pas',
  BoletoRetorno in 'model\BoletoRetorno.pas',
  Cartao in 'model\Cartao.pas',
  Categoria in 'model\Categoria.pas',
  Cedente in 'model\Cedente.pas',
  Compra in 'model\Compra.pas',
  CompraItem in 'model\CompraItem.pas',
  ConfiguracaoFiscal in 'model\ConfiguracaoFiscal.pas',
  ConfiguracaoFiscalCofins in 'model\ConfiguracaoFiscalCofins.pas',
  ConfiguracaoFiscalIcms in 'model\ConfiguracaoFiscalIcms.pas',
  ConfiguracaoFiscalIpi in 'model\ConfiguracaoFiscalIpi.pas',
  ConfiguracaoFiscalPis in 'model\ConfiguracaoFiscalPis.pas',
  Conta in 'model\Conta.pas',
  Contabilista in 'model\Contabilista.pas',
  Empresa in 'model\Empresa.pas',
  EmpresaConfiguracao in 'model\EmpresaConfiguracao.pas',
  FormaRecebimento in 'model\FormaRecebimento.pas',
  GrupoTributario in 'model\GrupoTributario.pas',
  Item in 'model\Item.pas',
  ItemCodigo in 'model\ItemCodigo.pas',
  ItemInventario in 'model\ItemInventario.pas',
  Model in 'model\Model.pas',
  Ncm in 'model\Ncm.pas',
  Nfe in 'model\Nfe.pas',
  NfeCana in 'model\NfeCana.pas',
  NfeCanaDeduc in 'model\NfeCanaDeduc.pas',
  NfeCanaFordia in 'model\NfeCanaFordia.pas',
  NfeCobrDup in 'model\NfeCobrDup.pas',
  NfeCobrFat in 'model\NfeCobrFat.pas',
  NfeCompra in 'model\NfeCompra.pas',
  NfeConfiguracao in 'model\NfeConfiguracao.pas',
  NfeDet in 'model\NfeDet.pas',
  NfeDetAdi in 'model\NfeDetAdi.pas',
  NfeDetArma in 'model\NfeDetArma.pas',
  NfeDetCofins in 'model\NfeDetCofins.pas',
  NfeDetCofinsSt in 'model\NfeDetCofinsSt.pas',
  NfeDetComb in 'model\NfeDetComb.pas',
  NfeDetDi in 'model\NfeDetDi.pas',
  NfeDetExport in 'model\NfeDetExport.pas',
  NfeDetIcms in 'model\NfeDetIcms.pas',
  NfeDetIcmsUfDest in 'model\NfeDetIcmsUfDest.pas',
  NfeDetIi in 'model\NfeDetIi.pas',
  NfeDetIpi in 'model\NfeDetIpi.pas',
  NfeDetIssqn in 'model\NfeDetIssqn.pas',
  NfeDetMed in 'model\NfeDetMed.pas',
  NfeDetPis in 'model\NfeDetPis.pas',
  NfeDetPisSt in 'model\NfeDetPisSt.pas',
  NfeDetRastro in 'model\NfeDetRastro.pas',
  NfeDetVeic in 'model\NfeDetVeic.pas',
  NfeEntrega in 'model\NfeEntrega.pas',
  NfeExporta in 'model\NfeExporta.pas',
  NfeInfadfisco in 'model\NfeInfadfisco.pas',
  NfeInfcpl in 'model\NfeInfcpl.pas',
  NfeNumero in 'model\NfeNumero.pas',
  NfePag in 'model\NfePag.pas',
  NfeRefCte in 'model\NfeRefCte.pas',
  NfeRefEcf in 'model\NfeRefEcf.pas',
  NfeRefNf in 'model\NfeRefNf.pas',
  NfeRefNfe in 'model\NfeRefNfe.pas',
  NfeRefNfp in 'model\NfeRefNfp.pas',
  NfeRetirada in 'model\NfeRetirada.pas',
  NfeTotalIcms in 'model\NfeTotalIcms.pas',
  NfeTotalIssqn in 'model\NfeTotalIssqn.pas',
  NfeTotalRettrib in 'model\NfeTotalRettrib.pas',
  NfeTransp in 'model\NfeTransp.pas',
  NfeTranspReboque in 'model\NfeTranspReboque.pas',
  NfeTranspRet in 'model\NfeTranspRet.pas',
  NfeTranspVeic in 'model\NfeTranspVeic.pas',
  NfeTranspVol in 'model\NfeTranspVol.pas',
  NfeTranspVolLacres in 'model\NfeTranspVolLacres.pas',
  OperacaoFiscal in 'model\OperacaoFiscal.pas',
  Pagamento in 'model\Pagamento.pas',
  Permission in 'model\Permission.pas',
  Pessoa in 'model\Pessoa.pas',
  Recebimento in 'model\Recebimento.pas',
  Role in 'model\Role.pas',
  Sped in 'model\Sped.pas',
  Terminal in 'model\Terminal.pas',
  Trasnferencia in 'model\Trasnferencia.pas',
  Turno in 'model\Turno.pas',
  Unidade in 'model\Unidade.pas',
  UnidadeConversao in 'model\UnidadeConversao.pas',
  UnidadeConversaoCodigo in 'model\UnidadeConversaoCodigo.pas',
  User in 'model\User.pas',
  Venda in 'model\Venda.pas',
  VendaItem in 'model\VendaItem.pas',
  VendaRecebimento in 'model\VendaRecebimento.pas',
  ViewCfCofins in 'model\ViewCfCofins.pas',
  ViewCfIcms in 'model\ViewCfIcms.pas',
  ViewCfIpi in 'model\ViewCfIpi.pas',
  ViewCfPis in 'model\ViewCfPis.pas',
  ViewContaExtrato in 'model\ViewContaExtrato.pas',
  ViewSped0150 in 'model\ViewSped0150.pas',
  ViewSped0190 in 'model\ViewSped0190.pas',
  ViewSped0200 in 'model\ViewSped0200.pas',
  ViewSpedC100 in 'model\ViewSpedC100.pas',
  ViewSpedC190 in 'model\ViewSpedC190.pas',
  Wt in 'model\Wt.pas',
  Repository in 'repository\Repository.pas',
  AuthService in 'service\AuthService.pas',
  Conexao in 'db\Conexao.pas',
  OrdemServico in 'model\OrdemServico.pas',
  uformOrdemServicoList in 'form\uformOrdemServicoList.pas' {formOrdemServicoList},
  uformConsultaCPF in 'form\uformConsultaCPF.pas' {formConsultaCPF},
  uformConsultaCNPJ in 'form\uformConsultaCNPJ.pas' {formConsultaCNPJ},
  uformOrdemServicoCreateEdit in 'form\uformOrdemServicoCreateEdit.pas' {formOrdemServicoCreateEdit},
  Dashboard in 'model\Dashboard.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TdmRepository, dmRepository);
  Application.CreateForm(TformPrincipal, formPrincipal);
  Application.Run;
end.
